"""Deployment-only readiness and production composition helpers.

This package is intentionally outside the research pipeline.  It verifies and
rehearses deployment state, resolves the formal S5 composition, and provides
the authoritative latest-date gate without changing frozen screener
semantics.
"""

from app.deployment.composition import (
    CANDIDATE_LIMIT_ENV,
    DEFAULT_CANDIDATE_LIMIT,
    HISTORY_OBSERVATIONS,
    PRODUCTION_COMPOSITION_CONTRACT_VERSION,
    PRODUCTION_S5_FACTORY_LOCATOR,
    UNIVERSE_SNAPSHOT_PATH_ENV,
    JsonUniverseSnapshotProvider,
    ProductionCompositionError,
    ProductionS5Composition,
    ProductionS5Configuration,
    SQLiteScreenerResearchDataset,
    create_s5,
    validate_production_s5_configuration,
)
from app.deployment.latest_date import (
    DEFAULT_LATEST_DATE_PROBE_SYMBOL,
    DEFAULT_LATEST_DATE_TIMEOUT_SECONDS,
    LATEST_DATE_PROVIDER_CONTRACT_VERSION,
    LATEST_DATE_PROBE_SYMBOL_ENV,
    LATEST_DATE_TIMEOUT_ENV,
    PRODUCTION_LATEST_DATE_FACTORY_LOCATOR,
    TWSE_LATEST_DATE_DATASET,
    TWSE_LATEST_DATE_SOURCE,
    LatestDateProviderError,
    LatestDateResolution,
    OfficialTwseLatestDateProvider,
    create_latest_date_provider,
)

from app.deployment.ds6_daily_preparation import (
    DEFAULT_DS6_CANDIDATE_LIMIT,
    DEFAULT_DS6_GRACE_END,
    DEFAULT_DS6_MAX_TWSE_ATTEMPTS,
    DEFAULT_DS6_RETRY_DELAY_SECONDS,
    DEFAULT_DS6_TARGET_OBSERVATIONS,
    DS6AmbiguousVersionError,
    DS6Configuration,
    DS6DailyPreparationCoordinator,
    DS6LatestDateError,
    DS6PreparationError,
    DS6SourcePreparation,
    DS6ResumeState,
    DS6_DAILY_PREPARATION_CONTRACT_VERSION,
    DS6_DAILY_PREPARATION_FACTORY_LOCATOR,
    DS6_METHODOLOGY_VERSION,
    DailyDatasetPreparationResult,
    DailyPreparationIntegrationResult,
    ExplicitDatasetVersionConsumer,
)

from app.deployment.readiness import (
    DEPLOYMENT_CONTRACT_VERSION,
    EXPECTED_SCHEMA_VERSION,
    EXPECTED_SOURCE_SCHEMA_VERSION,
    BackupVerification,
    DatabasePreflight,
    DeploymentReadinessError,
    MigrationRehearsal,
    RuntimePreflight,
    build_config_fingerprint,
    build_readiness_manifest,
    collect_database_preflight,
    create_verified_backup,
    rehearse_v9_to_v11,
    restore_verified_backup,
    run_runtime_preflight,
    sha256_file,
    verify_migration_file_hashes,
)

__all__ = [
    "BackupVerification",
    "CANDIDATE_LIMIT_ENV",
    "DEFAULT_DS6_CANDIDATE_LIMIT",
    "DEFAULT_DS6_GRACE_END",
    "DEFAULT_DS6_MAX_TWSE_ATTEMPTS",
    "DEFAULT_DS6_RETRY_DELAY_SECONDS",
    "DEFAULT_DS6_TARGET_OBSERVATIONS",
    "DEPLOYMENT_CONTRACT_VERSION",
    "DS6AmbiguousVersionError",
    "DS6Configuration",
    "DS6DailyPreparationCoordinator",
    "DS6LatestDateError",
    "DS6PreparationError",
    "DS6SourcePreparation",
    "DS6ResumeState",
    "DS6_DAILY_PREPARATION_CONTRACT_VERSION",
    "DS6_DAILY_PREPARATION_FACTORY_LOCATOR",
    "DS6_METHODOLOGY_VERSION",
    "DEFAULT_CANDIDATE_LIMIT",
    "DEFAULT_LATEST_DATE_PROBE_SYMBOL",
    "DEFAULT_LATEST_DATE_TIMEOUT_SECONDS",
    "DatabasePreflight",
    "DailyDatasetPreparationResult",
    "DailyPreparationIntegrationResult",
    "DeploymentReadinessError",
    "EXPECTED_SCHEMA_VERSION",
    "EXPECTED_SOURCE_SCHEMA_VERSION",
    "ExplicitDatasetVersionConsumer",
    "HISTORY_OBSERVATIONS",
    "LATEST_DATE_PROVIDER_CONTRACT_VERSION",
    "LATEST_DATE_PROBE_SYMBOL_ENV",
    "LATEST_DATE_TIMEOUT_ENV",
    "JsonUniverseSnapshotProvider",
    "LatestDateProviderError",
    "LatestDateResolution",
    "MigrationRehearsal",
    "OfficialTwseLatestDateProvider",
    "PRODUCTION_COMPOSITION_CONTRACT_VERSION",
    "PRODUCTION_LATEST_DATE_FACTORY_LOCATOR",
    "PRODUCTION_S5_FACTORY_LOCATOR",
    "ProductionCompositionError",
    "ProductionS5Composition",
    "ProductionS5Configuration",
    "RuntimePreflight",
    "SQLiteScreenerResearchDataset",
    "TWSE_LATEST_DATE_DATASET",
    "TWSE_LATEST_DATE_SOURCE",
    "UNIVERSE_SNAPSHOT_PATH_ENV",
    "build_config_fingerprint",
    "build_readiness_manifest",
    "collect_database_preflight",
    "create_verified_backup",
    "create_latest_date_provider",
    "create_s5",
    "rehearse_v9_to_v11",
    "restore_verified_backup",
    "run_runtime_preflight",
    "sha256_file",
    "validate_production_s5_configuration",
    "verify_migration_file_hashes",
]
