"""Persistence adapters."""

from .sqlite import (
    PipelineRunConflictError,
    PipelineRunError,
    PipelineRunInProgressError,
    PipelineRunStateError,
    SQLiteResearchRepository,
    StorageWriteResult,
)
from .history import (
    HistoricalSyncConflictError,
    HistoricalSyncError,
    HistoricalSyncInProgressError,
    HistoricalSyncStateError,
    SQLiteHistoricalSyncRepository,
)
from .cross_validation import (
    CrossValidationConflictError,
    CrossValidationError,
    CrossValidationInProgressError,
    CrossValidationStateError,
    SQLiteCrossValidationRepository,
)
from .historical_validation import (
    HistoricalValidationConflictError,
    HistoricalValidationError,
    HistoricalValidationInProgressError,
    HistoricalValidationStateError,
    SQLiteHistoricalValidationRepository,
)
from .daily_report import (
    DailyReportConflictError,
    DailyReportError,
    DailyReportStateError,
    SQLiteDailyReportRepository,
    StoredDailyResearchReport,
    StoredDailyResearchResult,
)
from .operations import (
    HealthSnapshot,
    HealthStatus,
    InvocationStatus,
    LeaseAcquireResult,
    LeaseUnavailableError,
    OperationLease,
    OperationLogEntry,
    OperationLogLevel,
    OperationsError,
    OperationsStateError,
    SQLiteOperationsRepository,
    SchedulerInvocation,
    health_status_for_operation,
    redact_operation_message,
)
from .dataset_versions import (
    DatasetMigrationResult,
    DatasetMigrationStateError,
    DatasetPersistenceIntegrityError,
    DatasetVersionMigrationRunner,
    DatasetVersionNotFoundError,
    DatasetVersionPersistenceResult,
    DatasetVersionRepository,
)
from .reconciliation import (
    DatasetReconciliationRepository,
    ReconciliationPersistenceError,
    ReconciliationPersistenceResult,
)

__all__ = [
    "PipelineRunConflictError",
    "PipelineRunError",
    "PipelineRunInProgressError",
    "PipelineRunStateError",
    "SQLiteResearchRepository",
    "StorageWriteResult",
    "HistoricalSyncConflictError",
    "HistoricalSyncError",
    "HistoricalSyncInProgressError",
    "HistoricalSyncStateError",
    "SQLiteHistoricalSyncRepository",
    "CrossValidationConflictError",
    "CrossValidationError",
    "CrossValidationInProgressError",
    "CrossValidationStateError",
    "SQLiteCrossValidationRepository",
    "HistoricalValidationConflictError",
    "HistoricalValidationError",
    "HistoricalValidationInProgressError",
    "HistoricalValidationStateError",
    "SQLiteHistoricalValidationRepository",
    "DailyReportConflictError",
    "DailyReportError",
    "DailyReportStateError",
    "SQLiteDailyReportRepository",
    "StoredDailyResearchReport",
    "StoredDailyResearchResult",
    "HealthSnapshot",
    "HealthStatus",
    "InvocationStatus",
    "LeaseAcquireResult",
    "LeaseUnavailableError",
    "OperationLease",
    "OperationLogEntry",
    "OperationLogLevel",
    "OperationsError",
    "OperationsStateError",
    "SQLiteOperationsRepository",
    "SchedulerInvocation",
    "health_status_for_operation",
    "redact_operation_message",
    "DatasetMigrationResult",
    "DatasetMigrationStateError",
    "DatasetPersistenceIntegrityError",
    "DatasetVersionMigrationRunner",
    "DatasetVersionNotFoundError",
    "DatasetVersionPersistenceResult",
    "DatasetVersionRepository",
    "DatasetReconciliationRepository",
    "ReconciliationPersistenceError",
    "ReconciliationPersistenceResult",
]
